"""incident_responses — what an emergency crew did, one row per state change

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-31

Autogenerated from db/models.py and then only renamed. Append-only: there is
no update path, because "when was the unit dispatched" is the question this
table exists to answer and an overwritten status column cannot answer it.

No foreign key to `incidents` on purpose — incidents live in an in-memory
deque today (see routers/incidents.py), so a constraint would reject every
insert. Adding it becomes correct the day M4 persists them.
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  ← keep: registers spatial types for this script
import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('incident_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_responses'))
    )
    op.create_index('ix_incident_responses_at', 'incident_responses', ['at'], unique=False)
    op.create_index('ix_incident_responses_incident_at', 'incident_responses', ['incident_id', sa.literal_column('at DESC')], unique=False)


def downgrade() -> None:
    op.drop_index('ix_incident_responses_incident_at', table_name='incident_responses')
    op.drop_index('ix_incident_responses_at', table_name='incident_responses')
    op.drop_table('incident_responses')
